import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { Providers } from '@/store/providers'
import '@/DB/conn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col h-screen'>
      <Providers>
      <Header />
      <main className='overflow-auto flex-1 flex flex-col justify-between'>
        <div>
        {children}
        </div>
        <Footer />
      </main>
      </Providers>
        </body>
    </html>
  )
}
